test:
  adapter:      <%= ENV['DATABASE'] || 'mysql2' %>
  database:     thinking_sphinx
  username:     <%= ENV['DATABASE'] == 'postgresql' ? ENV['USER'] : 'root' %>
  min_messages: warning
  encoding:     utf8
